# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  codacy: codacy/base@1.0.0

jobs:
  build:
    working_directory: ~/project
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:12.9.1
      - image: mongo:4.2.0

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
     - run:
          name: Coverage
          command: |
            if [ -n "$CODACY_PROJECT_TOKEN" ]; then
              cat ./coverage/lcov.info | node ./bin/codacy-coverage.js
            else
              echo "Skip sending coverage due to no provided codacy token!""
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:12.9.1
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master

workflows:
  version: 2
  install_and_test:
    jobs:
      - codacy/checkout_and_version
      - build:
          name: build_latest
          node_version: "latest"
          requires:
            - codacy/checkout_and_version
      - codacy/tag_version:
          filters:
            branches:
              only:
                - master
          name: tag_version
          context: CodacyAWS
          requires:
            - build_latest