version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  eslint: arrai/eslint@1.3.0
jobs:
  build:
    docker:
      - image: circleci/node:12.9.0
    working_directory: ~/project-mender

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.12'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # run lint before tests
      - run: # install expo for frontend build
         name: Install Expo CLI
         command: npm install -g expo-cli
      - run: # run frontend build
         name: frontend build
         path: frontend/
         command: npm install && npm start
      - run: # run backend tests with coverage
         name: backend-test with coverage
         path: backend/
         command: npm install && npm run coverage
      - store_test_results: # for storing unit test results
         path: backend/test-results.xml
      - store_artifacts: # archiving unit test results as store_test_results does not seem to be functioning
         path: backend/test-results.xml
      - store_artifacts:
         path: backend/coverage
