version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:12.9.0
      - image: mongo:4.2.0
      - image: debian:stretch
    working_directory: ~/project-mender

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.12'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run: # run tests
          name: test
          command: npm test
      - run: # run coverage report
          name: code-coverage
          command: 'npm run coverage'
      - run:
          command: |
            mkdir ~/project-mender/reports
      - store_artifacts:
          path: reports
      - run:
          command: |
            mkdir ~/project-mender/test-results
      - store_test_results:
          path: test-results
      # run ESLint test
    #   - store_artifacts:
    #       path: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage/index.html
          prefix: coverage
      - codecov/upload:
          file: coverage/index.html
