version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.0
      - image: mongo:4.2.0
      - image: debian:stretch
    working_directory: ~/project-mender

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.12'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run: # run tests
          name: test
          command: npm test
      - run: # run coverage report
          name: code-coverage
          command: 'npm run coverage'
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /test/artifact-1;
            mkdir /test/artifacts;
            echo "my artifact files in a dir" > /test/artifacts/artifact-2;
      - store_artifacts:
          path: /test/artifact-1
          destination: artifact-file
      - store_artifacts:
          path: /test/artifacts
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-report.html
          prefix: coverage
