export enum SectorType {
    'BUILDING' = 'BUILDING',
    'ELECTRICITY' = 'ELECTRICITY',
    'STRUCTURE' = 'STRUCTURE',
    'EXTERIOR' = 'EXTERIOR',
    'UTILITY' = 'UTILITY',
    'HVAC' = 'HVAC',
    'INTERIOR_FINISH' = 'INTERIOR_FINISH',
    'APPLIANCES' = 'APPLIANCES',
}
