export enum SectorType {
    'BUILDING' = 'BUILDING',
    'ELECTRICITY' = 'ELECTRICITY',
    'STRUCTURE' = 'STRUCTURE',
    'EXTERIOR' = 'EXTERIOR',
    'UTILITY' = 'UTILITY',
    'HVAC' = 'HVAC',
    'INTERIOR FINISH' = 'INTERIOR FINISH',
    'APPLIANCES AND FURNITURES' = 'APPLIANCES AND FURNITURES',
}
