export enum WorkOrderStatus {
    'ISSUED' = 'ISSUED',
    'CANCELLED' = 'CANCELLED',
    'COMPLETED' = 'COMPLETED',
    'OPEN_FOR_QUOTE' = 'OPEN_FOR_QUOTE',
    'QUOTE_RECEIVED' = 'QUOTE_RECEIVED',
}
