export enum WorkOrderQuery {
    'SECTORTYPE' = 'sectorType',
    'PAGESIZE' = 'pageSize',
    'PAGENUMBER' = 'pageNumber',
    'SEARCHTERM' = 'searchterm',
    'PROPERTYID' = 'propertyId',
    'WORKORDERTYPE' = 'workOrderType',
    'SERVICENEEDED' = 'serviceNeeded',
    'PRIORITYTYPE' = 'priorityType',
    'PRICEESTIMATE' = 'priceEstimate',
    'GREATERTHAN' = 'greaterThan',
    'GREATERTHANVALUE' = 'greaterThanValue',
    'LOWERTHAN' = 'lowerThan',
    'LOWERTHANVALUE' = 'lowerThanValue',
    'ID' = 'id',
    'DUEDATE' = 'dueDate',
    'CREATEDDATE' = 'createdDate',
    'SORTBY' = 'sortBy',
    'ORDERING'= 'ordering'
};